import { CHANNEL_PERMISSIONS } from "constants/permissions";

export const getChannelPermissions = (modulePermissions: string[] = []) => {
  const permissionsSet = new Set(modulePermissions);

  return {
    isCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_CREATE_ADMIN),
    isReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_READ_ADMIN),
    isUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_UPDATE_ADMIN),
    isDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DELETE_ADMIN),
    isPostsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_CREATE_ADMIN),
    isPostsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_READ_ADMIN),
    isPostsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_UPDATE_ADMIN),
    isPostsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_DELETE_ADMIN),
    isAnnouncementsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_CREATE_ADMIN),
    isAnnouncementsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_READ_ADMIN),
    isAnnouncementsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_UPDATE_ADMIN),
    isAnnouncementsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_DELETE_ADMIN),
    isAnnouncementsAcknowledgeAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_ACKNOWLEDGE_ADMIN),
    isAnnouncementsReportsAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_REPORTS_ADMIN),
    isAnnouncementsRemindersAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_REMINDERS_ADMIN),
    isReactionsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_CREATE_ADMIN),
    isReactionsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_READ_ADMIN),
    isReactionsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_UPDATE_ADMIN),
    isReactionsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_DELETE_ADMIN),
    isBookmarksCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_BOOKMARKS_CREATE_ADMIN),
    isBookmarksDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_BOOKMARKS_DELETE_ADMIN),
    isCommentsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_CREATE_ADMIN),
    isCommentsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_READ_ADMIN),
    isCommentsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_UPDATE_ADMIN),
    isCommentsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_DELETE_ADMIN),
    isRepliesCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_CREATE_ADMIN),
    isRepliesReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_READ_ADMIN),
    isRepliesUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_UPDATE_ADMIN),
    isRepliesDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_DELETE_ADMIN),
    isMembersCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_MEMBERS_CREATE_ADMIN),
    isMembersReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_MEMBERS_READ_ADMIN),
    isMembersUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_MEMBERS_UPDATE_ADMIN),
    isMembersDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_MEMBERS_DELETE_ADMIN),
    isJoinRequestsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_CREATE_ADMIN),
    isJoinRequestsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_READ_ADMIN),
    isJoinRequestsReactAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_REACT_ADMIN),
    isJoinRequestsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_UPDATE_ADMIN),
    isJoinRequestsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_DELETE_ADMIN),
    isLinksCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_LINKS_CREATE_ADMIN),
    isLinksReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_LINKS_READ_ADMIN),
    isLinksLaunchAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_LINKS_LAUNCH_ADMIN),
    isLinksUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_LINKS_UPDATE_ADMIN),
    isLinksDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_LINKS_DELETE_ADMIN),
    isDocumentsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_CREATE_ADMIN),
    isDocumentsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_READ_ADMIN),
    isDocumentsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_UPDATE_ADMIN),
    isDocumentsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_DELETE_ADMIN),
    isDocumentsLinkFoldersAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_LINK_FOLDERS_ADMIN),
    isDocumentsReadSitesAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_READ_SITES_ADMIN),
    isDocumentsCopyLinkAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_COPY_LINK_ADMIN),
    isDocumentsRenameAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_RENAME_ADMIN),
    isDocumentsDownloadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_DOWNLOAD_ADMIN),
    isDocumentCommentsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_CREATE_ADMIN),
    isDocumentCommentsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_UPDATE_ADMIN),
    isDocumentCommentsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_READ_ADMIN),
    isDocumentCommentsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_DELETE_ADMIN),
  };
};

export const getLearnerChannelPermissions = (modulePermissions: string[] = []) => {
  const permissionsSet = new Set(modulePermissions);

  return {
    isCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_CREATE_LEARNER),
    isReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_READ_LEARNER),
    isUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_UPDATE_LEARNER),
    isDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DELETE_LEARNER),
    isPostsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_CREATE_LEARNER),
    isPostsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_READ_LEARNER),
    isPostsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_UPDATE_LEARNER),
    isPostsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_POSTS_DELETE_LEARNER),
    isAnnouncementsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_READ_LEARNER),
    isAnnouncementsAcknowledgeAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_ANNOUNCEMENTS_ACKNOWLEDGE_LEARNER),
    isReactionsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_CREATE_LEARNER),
    isReactionsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_READ_LEARNER),
    isReactionsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_UPDATE_LEARNER),
    isReactionsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REACTIONS_DELETE_LEARNER),
    isBookmarksCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_BOOKMARKS_CREATE_LEARNER),
    isBookmarksDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_BOOKMARKS_DELETE_LEARNER),
    isCommentsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_CREATE_LEARNER),
    isCommentsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_READ_LEARNER),
    isCommentsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_UPDATE_LEARNER),
    isCommentsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_COMMENTS_DELETE_LEARNER),
    isRepliesCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_CREATE_LEARNER),
    isRepliesReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_READ_LEARNER),
    isRepliesUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_UPDATE_LEARNER),
    isRepliesDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_REPLIES_DELETE_LEARNER),
    isMembersReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_MEMBERS_READ_LEARNER),
    isJoinRequestsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_CREATE_LEARNER),
    isJoinRequestsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_READ_LEARNER),
    isJoinRequestsReactAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_REACT_LEARNER),
    isJoinRequestsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_UPDATE_LEARNER),
    isJoinRequestsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_JOIN_REQUESTS_DELETE_LEARNER),
    isLinksReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_LINKS_READ_LEARNER),
    isLinksLaunchAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_LINKS_LAUNCH_LEARNER),
    isDocumentsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_CREATE_LEARNER),
    isDocumentsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_READ_LEARNER),
    isDocumentsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_UPDATE_LEARNER),
    isDocumentsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_DELETE_LEARNER),
    isDocumentsLinkFolderAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_LINK_FOLDER_LEARNER),
    isDocumentsReadSitesAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_READ_SITES_LEARNER),
    isDocumentsCopyLinkAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_COPY_LINK_LEARNER),
    isDocumentsDownloadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENTS_DOWNLOAD_LEARNER),
    isDocumentCommentsCreateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_CREATE_LEARNER),
    isDocumentCommentsUpdateAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_UPDATE_LEARNER),
    isDocumentCommentsReadAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_READ_LEARNER),
    isDocumentCommentsDeleteAllowed: permissionsSet.has(CHANNEL_PERMISSIONS.CHANNELS_DOCUMENT_COMMENTS_DELETE_LEARNER),
  };
};
