export const ADMIN_MODULES = {
  COURSE_ADMIN: 'administrativeView:Course',
  TASK_ADMIN: 'administrativeView:Checklist',
  MENTORSHIP_ADMIN: 'administrativeView:Mentorship',
  USER_ADMIN: 'administrativeView:User',
  TEAM_ADMIN: 'administrativeView:Team',
  INSIGHT_ADMIN: 'administrativeView:Insights',
  BRANCH_ADMIN: 'administrativeView:SisterOrganization',
  EVENT_ADMIN: 'administrativeView:Event',
  EXTERNAL_TRAINING_ADMIN: 'administrativeView:ExternalTraining',
  REPORTS_ADMIN: 'administrativeView:Reports',
  FORUMS_ADMIN: 'administrativeView:Forums',
  ECOMMERCE_ADMIN: 'administrativeView:Ecommerce',
  LEARNING_PATH_ADMIN: 'administrativeView:LearningPath',
  SETTINGS_ADMIN: 'administrativeView:Settings',
  DASHBOARD_ADMIN: 'administrativeView:Dashboard',
  FEED_ADMIN: 'administrativeView:Feed',
  CHANNELS_ADMIN: 'administrativeView:Channels',
};

export const LEARNER_MODULES = {
  COURSE_LEARNER: 'learnerView:Course',
  EVENT_LEARNER: 'learnerView:Event',
  TASK_LEARNER: 'learnerView:Checklist',
  MENTORSHIP_LEARNER: 'learnerView:Mentorship',
  FORUMS_LEARNER: 'learnerView:Forums',
  LEARNING_PATH_LEARNER: 'learnerView:LearningPath',
  ECOMMERCE_LEARNER: 'learnerView:Ecommerce',
  SETTINGS_LEARNER: 'learnerView:Settings',
  DASHBOARD_LEARNER: 'learnerView:Dashboard',
  FEED_LEARNER: 'learnerView:Feed',
  CHANNELS_LEARNER: 'learnerView:Channels',
};

export const FEED_PERMISSIONS = {
  // ----------------------
  // Admin Permissions
  // ----------------------
  FEEDS_READ_ADMIN: 'feeds:read:admin',
  FEEDS_POSTS_CREATE_ADMIN: 'feeds:posts:create:admin',
  FEEDS_POSTS_READ_ADMIN: 'feeds:posts:read:admin',
  FEEDS_POSTS_UPDATE_ADMIN: 'feeds:posts:update:admin',
  FEEDS_POSTS_SCHEDULE_ADMIN: 'feeds:posts:schedule:admin',
  FEEDS_POSTS_DELETE_ADMIN: 'feeds:posts:delete:admin',
  FEEDS_POSTS_SHOUTOUT_CREATE_ADMIN: 'feeds:posts:shoutout:create:admin',
  FEEDS_POSTS_SHOUTOUT_READ_ADMIN: 'feeds:posts:shoutout:read:admin',
  FEEDS_POSTS_SHOUTOUT_UPDATE_ADMIN: 'feeds:posts:shoutout:update:admin',
  FEEDS_POSTS_SHOUTOUT_DELETE_ADMIN: 'feeds:posts:shoutout:delete:admin',
  FEEDS_POSTS_POLLS_CREATE_ADMIN: 'feeds:posts:polls:create:admin',
  FEEDS_POSTS_POLLS_READ_ADMIN: 'feeds:posts:polls:read:admin',
  FEEDS_POSTS_POLLS_UPDATE_ADMIN: 'feeds:posts:polls:update:admin',
  FEEDS_POSTS_POLLS_DELETE_ADMIN: 'feeds:posts:polls:delete:admin',
  FEEDS_POSTS_ANNOUNCEMENTS_CREATE_ADMIN: 'feeds:posts:announcements:create:admin',
  FEEDS_POSTS_ANNOUNCEMENTS_READ_ADMIN: 'feeds:posts:announcements:read:admin',
  FEEDS_POSTS_ANNOUNCEMENTS_UPDATE_ADMIN: 'feeds:posts:announcements:update:admin',
  FEEDS_POSTS_ANNOUNCEMENTS_DELETE_ADMIN: 'feeds:posts:announcements:delete:admin',
  FEEDS_POSTS_ANNOUNCEMENTS_ACKNOWLEDGE_ADMIN: 'feeds:posts:announcements:acknowledge:admin',
  FEEDS_POSTS_ANNOUNCEMENTS_REPORTS_ADMIN: 'feeds:posts:announcements:reports:admin',
  FEEDS_POSTS_ANNOUNCEMENTS_REMINDERS_ADMIN: 'feeds:posts:announcements:send_reminders:admin',
  FEEDS_REACTIONS_CREATE_ADMIN: 'feeds:reactions:create:admin',
  FEEDS_REACTIONS_READ_ADMIN: 'feeds:reactions:read:admin',
  FEEDS_REACTIONS_UPDATE_ADMIN: 'feeds:reactions:update:admin',
  FEEDS_REACTIONS_DELETE_ADMIN: 'feeds:reactions:delete:admin',
  FEEDS_BOOKMARKS_CREATE_ADMIN: 'feeds:bookmarks:create:admin',
  FEEDS_BOOKMARKS_DELETE_ADMIN: 'feeds:bookmarks:delete:admin',
  FEEDS_COMMENTS_CREATE_ADMIN: 'feeds:comments:create:admin',
  FEEDS_COMMENTS_READ_ADMIN: 'feeds:comments:read:admin',
  FEEDS_COMMENTS_UPDATE_ADMIN: 'feeds:comments:update:admin',
  FEEDS_COMMENTS_DELETE_ADMIN: 'feeds:comments:delete:admin',
  FEEDS_REPLIES_CREATE_ADMIN: 'feeds:replies:create:admin',
  FEEDS_REPLIES_READ_ADMIN: 'feeds:replies:read:admin',
  FEEDS_REPLIES_UPDATE_ADMIN: 'feeds:replies:update:admin',
  FEEDS_REPLIES_DELETE_ADMIN: 'feeds:replies:delete:admin',

  // ----------------------
  // Learner Permissions
  // ----------------------
  FEEDS_READ_LEARNER: 'feeds:read:learner',
  FEEDS_POSTS_CREATE_LEARNER: 'feeds:posts:create:learner',
  FEEDS_POSTS_READ_LEARNER: 'feeds:posts:read:learner',
  FEEDS_POSTS_UPDATE_LEARNER: 'feeds:posts:update:learner',
  FEEDS_POSTS_SCHEDULE_LEARNER: 'feeds:posts:schedule:learner',
  FEEDS_POSTS_DELETE_LEARNER: 'feeds:posts:delete:learner',
  FEEDS_POSTS_SHOUTOUT_CREATE_LEARNER: 'feeds:posts:shoutout:create:learner',
  FEEDS_POSTS_SHOUTOUT_READ_LEARNER: 'feeds:posts:shoutout:read:learner',
  FEEDS_POSTS_SHOUTOUT_UPDATE_LEARNER: 'feeds:posts:shoutout:update:learner',
  FEEDS_POSTS_SHOUTOUT_DELETE_LEARNER: 'feeds:posts:shoutout:delete:learner',
  FEEDS_POSTS_POLLS_CREATE_LEARNER: 'feeds:posts:polls:create:learner',
  FEEDS_POSTS_POLLS_READ_LEARNER: 'feeds:posts:polls:read:learner',
  FEEDS_POSTS_POLLS_UPDATE_LEARNER: 'feeds:posts:polls:update:learner',
  FEEDS_POSTS_POLLS_DELETE_LEARNER: 'feeds:posts:polls:delete:learner',
  FEEDS_POSTS_ANNOUNCEMENTS_READ_LEARNER: 'feeds:posts:announcements:read:learner',
  FEEDS_BOOKMARKS_CREATE_LEARNER: 'feeds:bookmarks:create:learner',
  FEEDS_BOOKMARKS_DELETE_LEARNER: 'feeds:bookmarks:delete:learner',
  FEEDS_COMMENTS_CREATE_LEARNER: 'feeds:comments:create:learner',
  FEEDS_COMMENTS_READ_LEARNER: 'feeds:comments:read:learner',
  FEEDS_COMMENTS_UPDATE_LEARNER: 'feeds:comments:update:learner',
  FEEDS_COMMENTS_DELETE_LEARNER: 'feeds:comments:delete:learner',
  FEEDS_REPLIES_CREATE_LEARNER: 'feeds:replies:create:learner',
  FEEDS_REPLIES_READ_LEARNER: 'feeds:replies:read:learner',
  FEEDS_REPLIES_UPDATE_LEARNER: 'feeds:replies:update:learner',
  FEEDS_REPLIES_DELETE_LEARNER: 'feeds:replies:delete:learner',
};

export const CHANNEL_PERMISSIONS = {
  // ----------------------
  // Admin Permissions
  // ----------------------
  CHANNELS_CREATE_ADMIN: 'channels:create:admin',
  CHANNELS_UPDATE_ADMIN: 'channels:update:admin',
  CHANNELS_DELETE_ADMIN: 'channels:delete:admin',
  CHANNELS_READ_ADMIN: 'channels:read:admin',
  CHANNELS_POSTS_CREATE_ADMIN: 'channels:posts:create:admin',
  CHANNELS_POSTS_READ_ADMIN: 'channels:posts:read:admin',
  CHANNELS_POSTS_UPDATE_ADMIN: 'channels:posts:update:admin',
  CHANNELS_POSTS_DELETE_ADMIN: 'channels:posts:delete:admin',
  CHANNELS_ANNOUNCEMENTS_CREATE_ADMIN: 'channels:announcements:create:admin',
  CHANNELS_ANNOUNCEMENTS_READ_ADMIN: 'channels:announcements:read:admin',
  CHANNELS_ANNOUNCEMENTS_UPDATE_ADMIN: 'channels:announcements:update:admin',
  CHANNELS_ANNOUNCEMENTS_DELETE_ADMIN: 'channels:announcements:delete:admin',
  CHANNELS_ANNOUNCEMENTS_ACKNOWLEDGE_ADMIN: 'channels:announcements:acknowledge:admin',
  CHANNELS_ANNOUNCEMENTS_REPORTS_ADMIN: 'channels:announcements:reports:admin',
  CHANNELS_ANNOUNCEMENTS_REMINDERS_ADMIN: 'channels:announcements:send_reminders:admin',
  CHANNELS_REACTIONS_CREATE_ADMIN: 'channels:reactions:create:admin',
  CHANNELS_REACTIONS_READ_ADMIN: 'channels:reactions:read:admin',
  CHANNELS_REACTIONS_UPDATE_ADMIN: 'channels:reactions:update:admin',
  CHANNELS_REACTIONS_DELETE_ADMIN: 'channels:reactions:delete:admin',
  CHANNELS_BOOKMARKS_CREATE_ADMIN: 'channels:bookmarks:create:admin',
  CHANNELS_BOOKMARKS_DELETE_ADMIN: 'channels:bookmarks:delete:admin',
  CHANNELS_COMMENTS_CREATE_ADMIN: 'channels:comments:create:admin',
  CHANNELS_COMMENTS_READ_ADMIN: 'channels:comments:read:admin',
  CHANNELS_COMMENTS_UPDATE_ADMIN: 'channels:comments:update:admin',
  CHANNELS_COMMENTS_DELETE_ADMIN: 'channels:comments:delete:admin',
  CHANNELS_REPLIES_CREATE_ADMIN: 'channels:replies:create:admin',
  CHANNELS_REPLIES_READ_ADMIN: 'channels:replies:read:admin',
  CHANNELS_REPLIES_UPDATE_ADMIN: 'channels:replies:update:admin',
  CHANNELS_REPLIES_DELETE_ADMIN: 'channels:replies:delete:admin',
  CHANNELS_MEMBERS_CREATE_ADMIN: 'channels:members:create:admin',
  CHANNELS_MEMBERS_READ_ADMIN: 'channels:members:read:admin',
  CHANNELS_MEMBERS_UPDATE_ADMIN: 'channels:members:update:admin',
  CHANNELS_MEMBERS_DELETE_ADMIN: 'channels:members:delete:admin',
  CHANNELS_JOIN_REQUESTS_CREATE_ADMIN: 'channels:join_requests:create:admin',
  CHANNELS_JOIN_REQUESTS_READ_ADMIN: 'channels:join_requests:read:admin',
  CHANNELS_JOIN_REQUESTS_REACT_ADMIN: 'channels:join_requests:react:admin',
  CHANNELS_JOIN_REQUESTS_UPDATE_ADMIN: 'channels:join_requests:update:admin',
  CHANNELS_JOIN_REQUESTS_DELETE_ADMIN: 'channels:join_requests:delete:admin',
  CHANNELS_LINKS_CREATE_ADMIN: 'channels:links:create:admin',
  CHANNELS_LINKS_READ_ADMIN: 'channels:links:read:admin',
  CHANNELS_LINKS_LAUNCH_ADMIN: 'channels:links:launch:admin',
  CHANNELS_LINKS_UPDATE_ADMIN: 'channels:links:update:admin',
  CHANNELS_LINKS_DELETE_ADMIN: 'channels:links:delete:admin',
  CHANNELS_DOCUMENTS_CREATE_ADMIN: 'channels:documents:create:admin',
  CHANNELS_DOCUMENTS_READ_ADMIN: 'channels:documents:read:admin',
  CHANNELS_DOCUMENTS_UPDATE_ADMIN: 'channels:documents:update:admin',
  CHANNELS_DOCUMENTS_DELETE_ADMIN: 'channels:documents:delete:admin',
  CHANNELS_DOCUMENTS_LINK_FOLDERS_ADMIN: 'channels:documents:link_folders:admin',
  CHANNELS_DOCUMENTS_READ_SITES_ADMIN: 'channels:documents:read_sites:admin',
  CHANNELS_DOCUMENTS_COPY_LINK_ADMIN: 'channels:documents:copy_link:admin',
  CHANNELS_DOCUMENTS_RENAME_ADMIN: 'channels:documents:rename:admin',
  CHANNELS_DOCUMENTS_DOWNLOAD_ADMIN: 'channels:documents:download:admin',
  CHANNELS_DOCUMENT_COMMENTS_CREATE_ADMIN: 'channels:document_comments:create:admin',
  CHANNELS_DOCUMENT_COMMENTS_UPDATE_ADMIN: 'channels:document_comments:update:admin',
  CHANNELS_DOCUMENT_COMMENTS_READ_ADMIN: 'channels:document_comments:read:admin',
  CHANNELS_DOCUMENT_COMMENTS_DELETE_ADMIN: 'channels:document_comments:delete:admin',

  // ----------------------
  // Learner Permissions
  // ----------------------
  CHANNELS_CREATE_LEARNER: 'channels:create:learner',
  CHANNELS_UPDATE_LEARNER: 'channels:update:learner',
  CHANNELS_DELETE_LEARNER: 'channels:delete:learner',
  CHANNELS_READ_LEARNER: 'channels:read:learner',
  CHANNELS_POSTS_CREATE_LEARNER: 'channels:posts:create:learner',
  CHANNELS_POSTS_READ_LEARNER: 'channels:posts:read:learner',
  CHANNELS_POSTS_UPDATE_LEARNER: 'channels:posts:update:learner',
  CHANNELS_POSTS_DELETE_LEARNER: 'channels:posts:delete:learner',
  CHANNELS_ANNOUNCEMENTS_READ_LEARNER: 'channels:announcements:read:learner',
  CHANNELS_ANNOUNCEMENTS_ACKNOWLEDGE_LEARNER: 'channels:announcements:acknowledge:learner',
  CHANNELS_REACTIONS_CREATE_LEARNER: 'channels:reactions:create:learner',
  CHANNELS_REACTIONS_READ_LEARNER: 'channels:reactions:read:learner',
  CHANNELS_REACTIONS_UPDATE_LEARNER: 'channels:reactions:update:learner',
  CHANNELS_REACTIONS_DELETE_LEARNER: 'channels:reactions:delete:learner',
  CHANNELS_BOOKMARKS_CREATE_LEARNER: 'channels:bookmarks:create:learner',
  CHANNELS_BOOKMARKS_DELETE_LEARNER: 'channels:bookmarks:delete:learner',
  CHANNELS_COMMENTS_CREATE_LEARNER: 'channels:comments:create:learner',
  CHANNELS_COMMENTS_READ_LEARNER: 'channels:comments:read:learner',
  CHANNELS_COMMENTS_UPDATE_LEARNER: 'channels:comments:update:learner',
  CHANNELS_COMMENTS_DELETE_LEARNER: 'channels:comments:delete:learner',
  CHANNELS_REPLIES_CREATE_LEARNER: 'channels:replies:create:learner',
  CHANNELS_REPLIES_READ_LEARNER: 'channels:replies:read:learner',
  CHANNELS_REPLIES_UPDATE_LEARNER: 'channels:replies:update:learner',
  CHANNELS_REPLIES_DELETE_LEARNER: 'channels:replies:delete:learner',
  CHANNELS_MEMBERS_READ_LEARNER: 'channels:members:read:learner',
  CHANNELS_JOIN_REQUESTS_CREATE_LEARNER: 'channels:join_requests:create:learner',
  CHANNELS_JOIN_REQUESTS_READ_LEARNER: 'channels:join_requests:read:learner',
  CHANNELS_JOIN_REQUESTS_REACT_LEARNER: 'channels:join_requests:react:learner',
  CHANNELS_JOIN_REQUESTS_UPDATE_LEARNER: 'channels:join_requests:update:learner',
  CHANNELS_JOIN_REQUESTS_DELETE_LEARNER: 'channels:join_requests:delete:learner',
  CHANNELS_LINKS_LAUNCH_LEARNER: 'channels:links:launch:learner',
  CHANNELS_LINKS_READ_LEARNER: 'channels:links:read:learner',
  CHANNELS_DOCUMENTS_CREATE_LEARNER: 'channels:documents:create:learner',
  CHANNELS_DOCUMENTS_READ_LEARNER: 'channels:documents:read:learner',
  CHANNELS_DOCUMENTS_UPDATE_LEARNER: 'channels:documents:update:learner',
  CHANNELS_DOCUMENTS_DELETE_LEARNER: 'channels:documents:delete:learner',
  CHANNELS_DOCUMENTS_LINK_FOLDER_LEARNER: 'channels:documents:link_folder:learner',
  CHANNELS_DOCUMENTS_READ_SITES_LEARNER: 'channels:documents:read_sites:learner',
  CHANNELS_DOCUMENTS_COPY_LINK_LEARNER: 'channels:documents:copy_link:learner',
  CHANNELS_DOCUMENTS_DOWNLOAD_LEARNER: 'channels:documents:download:learner',
  CHANNELS_DOCUMENT_COMMENTS_CREATE_LEARNER: 'channels:document_comments:create:learner',
  CHANNELS_DOCUMENT_COMMENTS_UPDATE_LEARNER: 'channels:document_comments:update:learner',
  CHANNELS_DOCUMENT_COMMENTS_READ_LEARNER: 'channels:document_comments:read:learner',
  CHANNELS_DOCUMENT_COMMENTS_DELETE_LEARNER: 'channels:document_comments:delete:learner',
};

export const APPS_PERMISSIONS = {
  // ----------------------
  // Admin Permissions
  // ----------------------
  APPS_READ_ADMIN: 'apps:read:admin',
  APPS_CREATE_ADMIN: 'apps:create:admin',
  APPS_UPDATE_ADMIN: 'apps:update:admin',
  APPS_DELETE_ADMIN: 'apps:delete:admin',
  APPS_FEATURED_READ_ADMIN: 'apps:featured:read:admin',
  APPS_FEATURED_CREATE_ADMIN: 'apps:featured:create:admin',
  APPS_FEATURED_UPDATE_ADMIN: 'apps:featured:update:admin',
  APPS_FEATURED_DELETE_ADMIN: 'apps:featured:delete:admin',

  // ----------------------
  // Learner Permissions
  // ----------------------
  APPS_READ_LEARNER: 'apps:read:learner',
  APPS_FEATURED_READ_LEARNER: 'apps:featured:read:learner',
};
