import { LEARNER_MODULES } from './permissions';

export const LEARNER_ACCESSIBLE_TRAININGS = {
  COURSE: LEARNER_MODULES.COURSE_LEARNER,
  PATH: LEARNER_MODULES.LEARNING_PATH_LEARNER,
  EVENT: LEARNER_MODULES.EVENT_LEARNER,
};
