export const userList = {
  results: [
    {
      name: 'Störfried Würgekloß',
      id: 10,
      image:
        'https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: 'Admin',
      active: true,
    },
    {
      name: 'Babacan Afet',
      id: 11,
      image: 'https://randomuser.me/api/portraits/med/women/42.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: 'Owner',
      active: true,
    },
    {
      name: 'Afet Villads',
      id: 12,
      image: '',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: false,
    },
    {
      name: 'Hulvejen København',
      id: 13,
      image: 'https://randomuser.me/api/portraits/med/men/70.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: 'Admin',
      active: true,
    },
    {
      name: 'Vladimir Putin',
      id: 14,
      image: 'https://randomuser.me/api/portraits/med/men/43.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: 'Pending',
      active: true,
    },
    {
      name: 'Pasaje Ruelas',
      id: 15,
      image: 'https://randomuser.me/api/portraits/med/women/56.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: true,
    },
    {
      name: 'SIlvia Zavala',
      id: 16,
      image: 'https://randomuser.me/api/portraits/med/men/56.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: true,
    },
    {
      name: 'Sara Murphy',
      id: 17,
      image: 'https://randomuser.me/api/portraits/med/women/71.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: true,
    },
    {
      name: 'Vladimir Putin',
      id: 18,
      image: 'https://randomuser.me/api/portraits/med/men/43.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: true,
    },
    {
      name: 'Pasaje Ruelas',
      id: 19,
      image: 'https://randomuser.me/api/portraits/med/women/56.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: true,
    },
    {
      name: 'Babacan Afet',
      id: 20,
      image: 'https://randomuser.me/api/portraits/med/women/42.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: false,
    },
    {
      name: 'Afet Villads',
      id: 21,
      image: 'https://randomuser.me/api/portraits/med/women/70.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: false,
    },
    {
      name: 'Hulvejen København',
      id: 22,
      image: 'https://randomuser.me/api/portraits/med/men/70.jpg',
      designation: 'Customer Success Manager',
      department: 'Sales',
      location: 'New York, USA',
      status: '',
      active: false,
    },
  ],
};
